-- MySQL Script generated by MySQL Workbench
-- Sun Nov 19 19:16:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stageavenir
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stageavenir
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stageavenir` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema stageavenir
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stageavenir
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stageavenir` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `stageavenir` ;

-- -----------------------------------------------------
-- Table `stageavenir`.`Cv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stageavenir`.`Cv` (
  `idCv` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idCv`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stageavenir`.`Catégorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stageavenir`.`Catégorie` (
  `idCatégorie` INT NOT NULL,
  `cursus` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idCatégorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stageavenir`.`Sous_Catégorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stageavenir`.`Sous_Catégorie` (
  `idSous_Catégorie` INT NOT NULL,
  `branche_étude` VARCHAR(45) NOT NULL,
  `Catégorie_idCatégorie` INT NOT NULL,
  PRIMARY KEY (`idSous_Catégorie`, `Catégorie_idCatégorie`),
  INDEX `fk_Sous_Catégorie_Catégorie1_idx` (`Catégorie_idCatégorie` ASC) VISIBLE,
  CONSTRAINT `fk_Sous_Catégorie_Catégorie1`
    FOREIGN KEY (`Catégorie_idCatégorie`)
    REFERENCES `stageavenir`.`Catégorie` (`idCatégorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stageavenir`.`Compte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stageavenir`.`Compte` (
  `idCompte` INT NOT NULL,
  `nom` VARCHAR(255) NULL,
  `prénom` VARCHAR(255) NULL,
  `no_étudiant` VARCHAR(255) NULL,
  `courriel` VARCHAR(255) NULL,
  `adresse` VARCHAR(255) NULL,
  `type_Entreprise` VARCHAR(255) NULL,
  `typeCompte` ENUM('etudiant', 'coordonnateur', 'entreprise', 'superviseur', 'admin') NOT NULL DEFAULT 'etudiant',
  `Cv_idCv` INT NOT NULL,
  `Catégorie_idCatégorie` INT NOT NULL,
  `Sous_Catégorie_idSous_Catégorie` INT NOT NULL,
  `Sous_Catégorie_Catégorie_idCatégorie` INT NOT NULL,
  PRIMARY KEY (`idCompte`, `Cv_idCv`, `Catégorie_idCatégorie`, `Sous_Catégorie_idSous_Catégorie`, `Sous_Catégorie_Catégorie_idCatégorie`),
  INDEX `fk_Etudiant_Cv_idx` (`Cv_idCv` ASC) VISIBLE,
  INDEX `fk_Etudiant_Catégorie1_idx` (`Catégorie_idCatégorie` ASC) VISIBLE,
  INDEX `fk_Compte_Sous_Catégorie1_idx` (`Sous_Catégorie_idSous_Catégorie` ASC, `Sous_Catégorie_Catégorie_idCatégorie` ASC) VISIBLE,
  CONSTRAINT `fk_Etudiant_Cv`
    FOREIGN KEY (`Cv_idCv`)
    REFERENCES `stageavenir`.`Cv` (`idCv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Etudiant_Catégorie1`
    FOREIGN KEY (`Catégorie_idCatégorie`)
    REFERENCES `stageavenir`.`Catégorie` (`idCatégorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compte_Sous_Catégorie1`
    FOREIGN KEY (`Sous_Catégorie_idSous_Catégorie` , `Sous_Catégorie_Catégorie_idCatégorie`)
    REFERENCES `stageavenir`.`Sous_Catégorie` (`idSous_Catégorie` , `Catégorie_idCatégorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stageavenir`.`Offre_Stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stageavenir`.`Offre_Stage` (
  `idOffre_Stage` INT NOT NULL,
  `titre_offre` VARCHAR(255) NOT NULL,
  `poste_offert` VARCHAR(255) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `favori` TINYINT NOT NULL DEFAULT 0,
  `est_rémunéré` TINYINT NOT NULL,
  `date_début` DATE NOT NULL,
  `date_fin` DATE NOT NULL,
  `Catégorie_idCatégorie` INT NOT NULL,
  `Compte_idCompte` INT NOT NULL,
  `Compte_Cv_idCv` INT NOT NULL,
  `Compte_Catégorie_idCatégorie` INT NOT NULL,
  PRIMARY KEY (`idOffre_Stage`, `Catégorie_idCatégorie`, `Compte_idCompte`, `Compte_Cv_idCv`, `Compte_Catégorie_idCatégorie`),
  INDEX `fk_Offre_Stage_Catégorie1_idx` (`Catégorie_idCatégorie` ASC) VISIBLE,
  INDEX `fk_Offre_Stage_Compte1_idx` (`Compte_idCompte` ASC, `Compte_Cv_idCv` ASC, `Compte_Catégorie_idCatégorie` ASC) VISIBLE,
  CONSTRAINT `fk_Offre_Stage_Catégorie1`
    FOREIGN KEY (`Catégorie_idCatégorie`)
    REFERENCES `stageavenir`.`Catégorie` (`idCatégorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offre_Stage_Compte1`
    FOREIGN KEY (`Compte_idCompte` , `Compte_Cv_idCv` , `Compte_Catégorie_idCatégorie`)
    REFERENCES `stageavenir`.`Compte` (`idCompte` , `Cv_idCv` , `Catégorie_idCatégorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stageavenir`.`Demande_stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stageavenir`.`Demande_stage` (
  `idDemande_stage` INT NOT NULL,
  `titre` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `poste_demandé` VARCHAR(255) NOT NULL,
  `Compte_idCompte` INT NOT NULL,
  `Compte_Cv_idCv` INT NOT NULL,
  PRIMARY KEY (`idDemande_stage`, `Compte_idCompte`, `Compte_Cv_idCv`),
  INDEX `fk_Demande_stage_Etudiant1_idx` (`Compte_idCompte` ASC, `Compte_Cv_idCv` ASC) VISIBLE,
  CONSTRAINT `fk_Demande_stage_Etudiant1`
    FOREIGN KEY (`Compte_idCompte` , `Compte_Cv_idCv`)
    REFERENCES `stageavenir`.`Compte` (`idCompte` , `Cv_idCv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stageavenir`.`Candidature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stageavenir`.`Candidature` (
  `idCandidature` INT NOT NULL,
  `acceptée` TINYINT NULL,
  `commentaire` VARCHAR(255) NULL,
  `Offre_Stage_idOffre_Stage` INT NOT NULL,
  `Demande_stage_idDemande_stage` INT NOT NULL,
  `Demande_stage_Compte_idCompte` INT NOT NULL,
  `Demande_stage_Compte_Cv_idCv` INT NOT NULL,
  PRIMARY KEY (`idCandidature`, `Offre_Stage_idOffre_Stage`, `Demande_stage_idDemande_stage`, `Demande_stage_Compte_idCompte`, `Demande_stage_Compte_Cv_idCv`),
  INDEX `fk_Candidature_Offre_Stage1_idx` (`Offre_Stage_idOffre_Stage` ASC) VISIBLE,
  INDEX `fk_Candidature_Demande_stage1_idx` (`Demande_stage_idDemande_stage` ASC, `Demande_stage_Compte_idCompte` ASC, `Demande_stage_Compte_Cv_idCv` ASC) VISIBLE,
  UNIQUE INDEX `idCandidature_UNIQUE` (`idCandidature` ASC) VISIBLE,
  CONSTRAINT `fk_Candidature_Offre_Stage1`
    FOREIGN KEY (`Offre_Stage_idOffre_Stage`)
    REFERENCES `stageavenir`.`Offre_Stage` (`idOffre_Stage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Candidature_Demande_stage1`
    FOREIGN KEY (`Demande_stage_idDemande_stage` , `Demande_stage_Compte_idCompte` , `Demande_stage_Compte_Cv_idCv`)
    REFERENCES `stageavenir`.`Demande_stage` (`idDemande_stage` , `Compte_idCompte` , `Compte_Cv_idCv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stageavenir`.`Document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stageavenir`.`Document` (
  `idDocument` INT NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  `Etudiant_idEtudiant` INT NOT NULL,
  `Etudiant_Cv_idCv` INT NOT NULL,
  `Candidature_idCandidature` INT NOT NULL,
  `Candidature_Offre_Stage_idOffre_Stage` INT NOT NULL,
  `Candidature_Offre_Stage_Entreprise_idEntreprise` INT NOT NULL,
  `Candidature_Demande_stage_idDemande_stage` INT NOT NULL,
  `Candidature_Demande_stage_Etudiant_idEtudiant` INT NOT NULL,
  `Candidature_Demande_stage_Etudiant_Cv_idCv` INT NOT NULL,
  PRIMARY KEY (`idDocument`, `Etudiant_idEtudiant`, `Etudiant_Cv_idCv`, `Candidature_idCandidature`, `Candidature_Offre_Stage_idOffre_Stage`, `Candidature_Offre_Stage_Entreprise_idEntreprise`, `Candidature_Demande_stage_idDemande_stage`, `Candidature_Demande_stage_Etudiant_idEtudiant`, `Candidature_Demande_stage_Etudiant_Cv_idCv`),
  INDEX `fk_Document_Etudiant1_idx` (`Etudiant_idEtudiant` ASC, `Etudiant_Cv_idCv` ASC) VISIBLE,
  INDEX `fk_Document_Candidature1_idx` (`Candidature_idCandidature` ASC, `Candidature_Offre_Stage_idOffre_Stage` ASC, `Candidature_Offre_Stage_Entreprise_idEntreprise` ASC, `Candidature_Demande_stage_idDemande_stage` ASC, `Candidature_Demande_stage_Etudiant_idEtudiant` ASC, `Candidature_Demande_stage_Etudiant_Cv_idCv` ASC) VISIBLE,
  CONSTRAINT `fk_Document_Etudiant1`
    FOREIGN KEY (`Etudiant_idEtudiant` , `Etudiant_Cv_idCv`)
    REFERENCES `stageavenir`.`Compte` (`idCompte` , `Cv_idCv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Document_Candidature1`
    FOREIGN KEY (`Candidature_idCandidature` , `Candidature_Offre_Stage_idOffre_Stage` , `Candidature_Demande_stage_idDemande_stage` , `Candidature_Demande_stage_Etudiant_idEtudiant` , `Candidature_Demande_stage_Etudiant_Cv_idCv`)
    REFERENCES `stageavenir`.`Candidature` (`idCandidature` , `Offre_Stage_idOffre_Stage` , `Demande_stage_idDemande_stage` , `Demande_stage_Compte_idCompte` , `Demande_stage_Compte_Cv_idCv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stageavenir`.`Accord_Stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stageavenir`.`Accord_Stage` (
  `idAccord_Stage` INT NOT NULL,
  `titre` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `Candidature_idCandidature` INT NOT NULL,
  `Candidature_Offre_Stage_idOffre_Stage` INT NOT NULL,
  `Candidature_Offre_Stage_Entreprise_idEntreprise` INT NOT NULL,
  `Candidature_Demande_stage_idDemande_stage` INT NOT NULL,
  `Candidature_Demande_stage_Compte_idCompte` INT NOT NULL,
  `Candidature_Demande_stage_Compte_Cv_idCv` INT NOT NULL,
  `Compte_idCompte` INT NOT NULL,
  `Compte_Cv_idCv` INT NOT NULL,
  `Compte_Catégorie_idCatégorie` INT NOT NULL,
  PRIMARY KEY (`idAccord_Stage`, `Candidature_idCandidature`, `Candidature_Offre_Stage_idOffre_Stage`, `Candidature_Offre_Stage_Entreprise_idEntreprise`, `Candidature_Demande_stage_idDemande_stage`, `Candidature_Demande_stage_Compte_idCompte`, `Candidature_Demande_stage_Compte_Cv_idCv`, `Compte_idCompte`, `Compte_Cv_idCv`, `Compte_Catégorie_idCatégorie`),
  INDEX `fk_Accord_Stage_Candidature1_idx` (`Candidature_idCandidature` ASC, `Candidature_Offre_Stage_idOffre_Stage` ASC, `Candidature_Offre_Stage_Entreprise_idEntreprise` ASC, `Candidature_Demande_stage_idDemande_stage` ASC, `Candidature_Demande_stage_Compte_idCompte` ASC, `Candidature_Demande_stage_Compte_Cv_idCv` ASC) VISIBLE,
  INDEX `fk_Accord_Stage_Compte1_idx` (`Compte_idCompte` ASC, `Compte_Cv_idCv` ASC, `Compte_Catégorie_idCatégorie` ASC) VISIBLE,
  CONSTRAINT `fk_Accord_Stage_Candidature1`
    FOREIGN KEY (`Candidature_idCandidature` , `Candidature_Offre_Stage_idOffre_Stage` , `Candidature_Demande_stage_idDemande_stage` , `Candidature_Demande_stage_Compte_idCompte` , `Candidature_Demande_stage_Compte_Cv_idCv`)
    REFERENCES `stageavenir`.`Candidature` (`idCandidature` , `Offre_Stage_idOffre_Stage` , `Demande_stage_idDemande_stage` , `Demande_stage_Compte_idCompte` , `Demande_stage_Compte_Cv_idCv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Accord_Stage_Compte1`
    FOREIGN KEY (`Compte_idCompte` , `Compte_Cv_idCv` , `Compte_Catégorie_idCatégorie`)
    REFERENCES `stageavenir`.`Compte` (`idCompte` , `Cv_idCv` , `Catégorie_idCatégorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stageavenir`.`Demande_Publication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stageavenir`.`Demande_Publication` (
  `idDemande_Publication` INT NOT NULL,
  `accepté` TINYINT NULL,
  `Offre_Stage_idOffre_Stage` INT NOT NULL,
  `Compte_idEtudiant` INT NOT NULL,
  `Compte_Cv_idCv` INT NOT NULL,
  `Compte_Catégorie_idCatégorie` INT NOT NULL,
  `Compte_Sous_Catégorie_idSous_Catégorie` INT NOT NULL,
  `Compte_Sous_Catégorie_Catégorie_idCatégorie` INT NOT NULL,
  PRIMARY KEY (`idDemande_Publication`, `Offre_Stage_idOffre_Stage`, `Compte_idEtudiant`, `Compte_Cv_idCv`, `Compte_Catégorie_idCatégorie`, `Compte_Sous_Catégorie_idSous_Catégorie`, `Compte_Sous_Catégorie_Catégorie_idCatégorie`),
  INDEX `fk_Demande_Publication_Offre_Stage1_idx` (`Offre_Stage_idOffre_Stage` ASC) VISIBLE,
  INDEX `fk_Demande_Publication_Compte1_idx` (`Compte_idEtudiant` ASC, `Compte_Cv_idCv` ASC, `Compte_Catégorie_idCatégorie` ASC, `Compte_Sous_Catégorie_idSous_Catégorie` ASC, `Compte_Sous_Catégorie_Catégorie_idCatégorie` ASC) VISIBLE,
  CONSTRAINT `fk_Demande_Publication_Offre_Stage1`
    FOREIGN KEY (`Offre_Stage_idOffre_Stage`)
    REFERENCES `stageavenir`.`Offre_Stage` (`idOffre_Stage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Demande_Publication_Compte1`
    FOREIGN KEY (`Compte_idEtudiant` , `Compte_Cv_idCv` , `Compte_Catégorie_idCatégorie` , `Compte_Sous_Catégorie_idSous_Catégorie` , `Compte_Sous_Catégorie_Catégorie_idCatégorie`)
    REFERENCES `stageavenir`.`Compte` (`idCompte` , `Cv_idCv` , `Catégorie_idCatégorie` , `Sous_Catégorie_idSous_Catégorie` , `Sous_Catégorie_Catégorie_idCatégorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stageavenir`.`Comprétence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stageavenir`.`Comprétence` (
  `idComprétence` INT NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `Etudiant_idEtudiant` INT NOT NULL,
  `Etudiant_Cv_idCv` INT NOT NULL,
  `Etudiant_Catégorie_idCatégorie` INT NOT NULL,
  PRIMARY KEY (`idComprétence`, `Etudiant_idEtudiant`, `Etudiant_Cv_idCv`, `Etudiant_Catégorie_idCatégorie`),
  INDEX `fk_Comprétence_Etudiant1_idx` (`Etudiant_idEtudiant` ASC, `Etudiant_Cv_idCv` ASC, `Etudiant_Catégorie_idCatégorie` ASC) VISIBLE,
  CONSTRAINT `fk_Comprétence_Etudiant1`
    FOREIGN KEY (`Etudiant_idEtudiant` , `Etudiant_Cv_idCv` , `Etudiant_Catégorie_idCatégorie`)
    REFERENCES `stageavenir`.`Compte` (`idCompte` , `Cv_idCv` , `Catégorie_idCatégorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stageavenir`.`Compte_has_Compte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stageavenir`.`Compte_has_Compte` (
  `Compte_idEtudiant` INT NOT NULL,
  `Compte_Cv_idCv` INT NOT NULL,
  `Compte_Coordonnateur_idCoordonnateur` INT NOT NULL,
  `Compte_Catégorie_idCatégorie` INT NOT NULL,
  `Compte_idEtudiant1` INT NOT NULL,
  `Compte_Cv_idCv1` INT NOT NULL,
  `Compte_Coordonnateur_idCoordonnateur1` INT NOT NULL,
  `Compte_Catégorie_idCatégorie1` INT NOT NULL,
  PRIMARY KEY (`Compte_idEtudiant`, `Compte_Cv_idCv`, `Compte_Coordonnateur_idCoordonnateur`, `Compte_Catégorie_idCatégorie`, `Compte_idEtudiant1`, `Compte_Cv_idCv1`, `Compte_Coordonnateur_idCoordonnateur1`, `Compte_Catégorie_idCatégorie1`),
  INDEX `fk_Compte_has_Compte_Compte2_idx` (`Compte_idEtudiant1` ASC, `Compte_Cv_idCv1` ASC, `Compte_Coordonnateur_idCoordonnateur1` ASC, `Compte_Catégorie_idCatégorie1` ASC) VISIBLE,
  INDEX `fk_Compte_has_Compte_Compte1_idx` (`Compte_idEtudiant` ASC, `Compte_Cv_idCv` ASC, `Compte_Coordonnateur_idCoordonnateur` ASC, `Compte_Catégorie_idCatégorie` ASC) VISIBLE,
  CONSTRAINT `fk_Compte_has_Compte_Compte1`
    FOREIGN KEY (`Compte_idEtudiant` , `Compte_Cv_idCv` , `Compte_Catégorie_idCatégorie`)
    REFERENCES `stageavenir`.`Compte` (`idCompte` , `Cv_idCv` , `Catégorie_idCatégorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compte_has_Compte_Compte2`
    FOREIGN KEY (`Compte_idEtudiant1` , `Compte_Cv_idCv1` , `Compte_Catégorie_idCatégorie1`)
    REFERENCES `stageavenir`.`Compte` (`idCompte` , `Cv_idCv` , `Catégorie_idCatégorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `stageavenir` ;




